export class Cat {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly color: Color,
    public readonly gender: Gender,
    public readonly status: Status,
    public readonly description: string | null,
    public readonly photos: string[],
    public readonly birthDate: Date | null,
    public readonly isNeutered: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  static create(
    name: string,
    color: Color,
    gender: Gender,
    status: Status,
    photos: string[],
    isNeutered: boolean,
    description?: string,
    birthDate?: Date,
  ): Cat {
    const now = new Date();
    return new Cat(
      '', // ID will be generated by the database
      name,
      color,
      gender,
      status,
      description ?? null,
      photos,
      birthDate ?? null,
      isNeutered,
      now,
      now,
    );
  }

  update(data: {
    name?: string;
    age?: number;
    breed?: string | null;
    description?: string | null;
  }): Cat {
    return new Cat(
      this.id,
      data.name ?? this.name,
      data.age ?? this.age,
      data.breed !== undefined ? data.breed : this.breed,
      data.description !== undefined ? data.description : this.description,
      this.createdAt,
      new Date(), // Updated timestamp
    );
  }
}

export enum Color {
  BLACK, // Preto
  WHITE, // Branco
  GRAY, // Cinza
  ORANGE, // Laranja
  CREAM, // Creme
  BROWN, // Marrom
  CALICO, // Tricolor (branco + preto + laranja)
  TORTOISESHELL, // Escama de tartaruga (preto + laranja mesclado)
  TABBY_BROWN, // Tigrado marrom
  TABBY_GRAY, // Tigrado cinza
  TABBY_ORANGE, // Tigrado laranja
  BICOLOR_BLACK, // Preto e branco
  BICOLOR_GRAY, // Cinza e branco
  BICOLOR_ORANGE, // Laranja e branco
  POINT, // Siamês (cor clara no corpo, extremidades escuras)
  VAN, // Quase todo branco com algumas marcas
  SHADED, // Sombreado (pelagem gradiente)
  SMOKE, // Fumaça (pelagem escura com raiz clara)
  MINK, // Mink (pelagem de contraste suave)
}

export enum Gender {
  MALE,
  FEMALE,
}

export enum Status {
  AVAILABLE,
  ADOPTED,
}
