export class Cat {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly age: number,
    public readonly breed: string | null,
    public readonly description: string | null,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  static create(
    name: string,
    age: number,
    breed?: string,
    description?: string,
  ): Cat {
    const now = new Date();
    return new Cat(
      '', // ID will be generated by the database
      name,
      age,
      breed || null,
      description || null,
      now,
      now,
    );
  }

  update(data: {
    name?: string;
    age?: number;
    breed?: string | null;
    description?: string | null;
  }): Cat {
    return new Cat(
      this.id,
      data.name ?? this.name,
      data.age ?? this.age,
      data.breed !== undefined ? data.breed : this.breed,
      data.description !== undefined ? data.description : this.description,
      this.createdAt,
      new Date(), // Updated timestamp
    );
  }
}
