import { CatStatus, Color, Gender } from '../enums/cat.enums';

export class Cat {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly color: Color,
    public readonly gender: Gender,
    public readonly status: CatStatus,
    public readonly description: string | null,
    public readonly photos: string[] | null,
    public readonly birthDate: Date | null,
    public readonly isNeutered: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  static create(
    name: string,
    color: Color,
    gender: Gender,
    status: CatStatus,
    photos: string[],
    isNeutered: boolean,
    description?: string,
    birthDate?: Date,
  ): Cat {
    const now = new Date();
    return new Cat(
      '', // ID will be generated by the database
      name,
      color,
      gender,
      status,
      description ?? null,
      photos,
      birthDate ?? null,
      isNeutered,
      now,
      now,
    );
  }

  update(data: {
    name?: string;
    color?: Color;
    gender?: Gender;
    status?: CatStatus;
    photos?: string[];
    isNeutered?: boolean;
    description?: string;
    birthDate?: Date;
  }): Cat {
    return new Cat(
      this.id,
      data.name ?? this.name,
      data.color ?? this.color,
      data.gender ?? this.gender,
      data.status ?? this.status,
      data.description !== undefined ? data.description : this.description,
      data.photos ?? this.photos,
      data.birthDate ?? this.birthDate,
      data.isNeutered ?? this.isNeutered,
      this.createdAt,
      new Date(), // Updated timestamp
    );
  }
}
